In [881]:
import pandas as pd
import numpy as np

In [930]:
data=pd.read_csv("D:\\MachineCourse\\MachineLearnig\\Data\\Data\\2.1 Linear Regression\\houses.csv")

In [931]:
data.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0       3.0       1.00       1180.0    5650.0     1.0         0.0   0.0   
1       3.0       2.25       2570.0    7242.0     2.0         0.0   0.0   
2       2.0       1.00        770.0   10000.0     1.0         0.0   0.0   
3       4.0       3.00       1960.0    5000.0     1.0         0.0   0.0   
4       3.0       2.00       1680.0    8080.0     1.0         0.0   0.0   

   condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        3.0    7.0      1180.0            0.0    1955.0           0.0   
1        3.0    7.0      2170.0          400.0    1951.0        1991.0   
2        3.0    6.0       770.0            0.0    1933.0           0.0   
3        5.0    7.0      1050.0          910.0    1965.0           0.0   
4        3.0    8.0      1680.0            0.0    1987.0           0.0   

   zipcode      lat     long  sqft_living15  price  
0  98178.0  47.5112 -122.257         1340.0  22.19  
1  98125.0  47.7210 -122.319         1690.0  53.80  
2  98028.0  47.7379 -122.233         2720.0  18.00  
3  98136.0  47.5208 -122.393         1360.0  60.40  
4  98074.0  47.6168 -122.045         1800.0  51.00

In [932]:
data.tail()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
995       4.0       2.50       1860.0    6325.0     2.0         0.0   0.0   
996       2.0       2.75       1590.0   20917.0     1.5         0.0   0.0   
997       2.0       1.00        850.0    2340.0     1.0         0.0   0.0   
998       2.0       1.00       1030.0    4188.0     1.0         0.0   0.0   
999       NaN        NaN          NaN       NaN     NaN         NaN   NaN   

     condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
995        4.0    7.0      1860.0            0.0    1991.0           0.0   
996        3.0    5.0      1590.0            0.0    1920.0           0.0   
997        3.0    7.0       850.0            0.0    1922.0           0.0   
998        3.0    8.0      1030.0            0.0    1981.0           0.0   
999        NaN    NaN         NaN            NaN       NaN           NaN   

     zipcode      lat     long  sqft_living15   price  
995  98038.0  47.3492 -122.030         1860.0  29.100  
996  98001.0  47.2786 -122.250         1310.0  19.995  
997  98105.0  47.6707 -122.328         1300.0  55.350  
998  98038.0  47.3738 -122.057         1450.0  18.995  
999      NaN      NaN      NaN            NaN     NaN

In [933]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   bedrooms       999 non-null    float64
 1   bathrooms      999 non-null    float64
 2   sqft_living    999 non-null    float64
 3   sqft_lot       999 non-null    float64
 4   floors         999 non-null    float64
 5   waterfront     999 non-null    float64
 6   view           999 non-null    float64
 7   condition      999 non-null    float64
 8   grade          999 non-null    float64
 9   sqft_above     999 non-null    float64
 10  sqft_basement  999 non-null    float64
 11  yr_built       999 non-null    float64
 12  yr_renovated   999 non-null    float64
 13  zipcode        999 non-null    float64
 14  lat            999 non-null    float64
 15  long           999 non-null    float64
 16  sqft_living15  999 non-null    float64
 17  price          999 non-null    float64
dtypes: float6

In [934]:
data.isnull()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront   view  \
0       False      False        False     False   False       False  False   
1       False      False        False     False   False       False  False   
2       False      False        False     False   False       False  False   
3       False      False        False     False   False       False  False   
4       False      False        False     False   False       False  False   
..        ...        ...          ...       ...     ...         ...    ...   
995     False      False        False     False   False       False  False   
996     False      False        False     False   False       False  False   
997     False      False        False     False   False       False  False   
998     False      False        False     False   False       False  False   
999      True       True         True      True    True        True   True   

     condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        False  False       False          False     False         False   
1        False  False       False          False     False         False   
2        False  False       False          False     False         False   
3        False  False       False          False     False         False   
4        False  False       False          False     False         False   
..         ...    ...         ...            ...       ...           ...   
995      False  False       False          False     False         False   
996      False  False       False          False     False         False   
997      False  False       False          False     False         False   
998      False  False       False          False     False         False   
999       True   True        True           True      True          True   

     zipcode    lat   long  sqft_living15  price  
0      False  False  False          False  False  
1      False  False  False          False  False  
2      False  False  False          False  False  
3      False  False  False          False  False  
4      False  False  False          False  False  
..       ...    ...    ...            ...    ...  
995    False  False  False          False  False  
996    False  False  False          False  False  
997    False  False  False          False  False  
998    False  False  False          False  False  
999     True   True   True           True   True  

[1000 rows x 18 columns]

In [935]:
data.value_counts()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  zipcode  lat      long      sqft_living15  price 
0.0       0.00       3064.0       4764.0    3.5     0.0         2.0   3.0        7.0    3064.0      0.0            1990.0    0.0           98102.0  47.6362  -122.322  2360.0         110.00    1
4.0       1.75       2330.0       5000.0    1.5     0.0         0.0   4.0        7.0    1510.0      820.0          1929.0    0.0           98117.0  47.6823  -122.368  1460.0         68.75     1
                     1760.0       7300.0    1.0     0.0         0.0   3.0        7.0    880.0       880.0          1956.0    0.0           98008.0  47.6034  -122.125  1680.0         38.00     1
                                  11180.0   1.0     0.0         0.0   4.0        8.0    1760.0      0.0            1968.0    0.0           98059.0  47.4715  -122.118  1730.0         32.00     1
                     1800.0       4

In [936]:
data.describe()

bedrooms   bathrooms  sqft_living       sqft_lot      floors  \
count  999.000000  999.000000   999.000000     999.000000  999.000000   
mean     3.349349    2.045796  2051.397397   14707.242242    1.446947   
std      0.852367    0.721983   888.351113   28975.077254    0.517420   
min      0.000000    0.000000   380.000000     649.000000    1.000000   
25%      3.000000    1.500000  1405.000000    5419.000000    1.000000   
50%      3.000000    2.000000  1900.000000    8040.000000    1.000000   
75%      4.000000    2.500000  2475.000000   11508.500000    2.000000   
max      7.000000    5.000000  6070.000000  315374.000000    3.500000   

       waterfront        view   condition       grade   sqft_above  \
count  999.000000  999.000000  999.000000  999.000000   999.000000   
mean     0.008008    0.237237    3.464464    7.605606  1750.233233   
std      0.089173    0.765472    0.689521    1.160734   790.466905   
min      0.000000    0.000000    1.000000    4.000000   380.000000   
25%      0.000000    0.000000    3.000000    7.000000  1190.000000   
50%      0.000000    0.000000    3.000000    7.000000  1540.000000   
75%      0.000000    0.000000    4.000000    8.000000  2135.000000   
max      1.000000    4.000000    5.000000   12.000000  6070.000000   

       sqft_basement     yr_built  yr_renovated       zipcode         lat  \
count     999.000000   999.000000    999.000000    999.000000  999.000000   
mean      301.164164  1969.030030     81.830831  98074.441441   47.549720   
std       451.023402    28.198607    395.767918     52.545832    0.141558   
min         0.000000  1900.000000      0.000000  98001.000000   47.177500   
25%         0.000000  1952.000000      0.000000  98032.000000   47.443000   
50%         0.000000  1974.000000      0.000000  98058.000000   47.563600   
75%       580.000000  1992.000000      0.000000  98116.000000   47.673400   
max      2060.000000  2015.000000   2014.000000  98199.000000   47.777600   

             long  sqft_living15       price  
count  999.000000     999.000000  999.000000  
mean  -122.207406    1986.813814   52.071452  
std      0.139564     670.723475   33.974907  
min   -122.490000     830.000000    8.000000  
25%   -122.322500    1490.000000   30.980000  
50%   -122.218000    1850.000000   43.500000  
75%   -122.118000    2360.000000   63.446250  
max   -121.709000    4760.000000  308.000000

In [937]:
data

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0         3.0       1.00       1180.0    5650.0     1.0         0.0   0.0   
1         3.0       2.25       2570.0    7242.0     2.0         0.0   0.0   
2         2.0       1.00        770.0   10000.0     1.0         0.0   0.0   
3         4.0       3.00       1960.0    5000.0     1.0         0.0   0.0   
4         3.0       2.00       1680.0    8080.0     1.0         0.0   0.0   
..        ...        ...          ...       ...     ...         ...   ...   
995       4.0       2.50       1860.0    6325.0     2.0         0.0   0.0   
996       2.0       2.75       1590.0   20917.0     1.5         0.0   0.0   
997       2.0       1.00        850.0    2340.0     1.0         0.0   0.0   
998       2.0       1.00       1030.0    4188.0     1.0         0.0   0.0   
999       NaN        NaN          NaN       NaN     NaN         NaN   NaN   

     condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0          3.0    7.0      1180.0            0.0    1955.0           0.0   
1          3.0    7.0      2170.0          400.0    1951.0        1991.0   
2          3.0    6.0       770.0            0.0    1933.0           0.0   
3          5.0    7.0      1050.0          910.0    1965.0           0.0   
4          3.0    8.0      1680.0            0.0    1987.0           0.0   
..         ...    ...         ...            ...       ...           ...   
995        4.0    7.0      1860.0            0.0    1991.0           0.0   
996        3.0    5.0      1590.0            0.0    1920.0           0.0   
997        3.0    7.0       850.0            0.0    1922.0           0.0   
998        3.0    8.0      1030.0            0.0    1981.0           0.0   
999        NaN    NaN         NaN            NaN       NaN           NaN   

     zipcode      lat     long  sqft_living15   price  
0    98178.0  47.5112 -122.257         1340.0  22.190  
1    98125.0  47.7210 -122.319         1690.0  53.800  
2    98028.0  47.7379 -122.233         2720.0  18.000  
3    98136.0  47.5208 -122.393         1360.0  60.400  
4    98074.0  47.6168 -122.045         1800.0  51.000  
..       ...      ...      ...            ...     ...  
995  98038.0  47.3492 -122.030         1860.0  29.100  
996  98001.0  47.2786 -122.250         1310.0  19.995  
997  98105.0  47.6707 -122.328         1300.0  55.350  
998  98038.0  47.3738 -122.057         1450.0  18.995  
999      NaN      NaN      NaN            NaN     NaN  

[1000 rows x 18 columns]

In [938]:
data=data.dropna()

In [939]:
x = data[['bedrooms', 'bathrooms', 'floors']]

In [940]:
x

bedrooms  bathrooms  floors
0         3.0       1.00     1.0
1         3.0       2.25     2.0
2         2.0       1.00     1.0
3         4.0       3.00     1.0
4         3.0       2.00     1.0
..        ...        ...     ...
994       2.0       1.00     1.0
995       4.0       2.50     2.0
996       2.0       2.75     1.5
997       2.0       1.00     1.0
998       2.0       1.00     1.0

[999 rows x 3 columns]

In [941]:
y=data['price']

In [942]:
def convert_x_y(x,y):
    x=x.values.tolist()
    y=y.values.tolist()
    return x,y
    

In [943]:
x,y=convert_x_y(x,y)

In [944]:
x

[[3.0, 1.0, 1.0],
 [3.0, 2.25, 2.0],
 [2.0, 1.0, 1.0],
 [4.0, 3.0, 1.0],
 [3.0, 2.0, 1.0],
 [4.0, 4.5, 1.0],
 [3.0, 2.25, 2.0],
 [3.0, 1.5, 1.0],
 [3.0, 1.0, 1.0],
 [3.0, 2.5, 2.0],
 [3.0, 2.5, 1.0],
 [2.0, 1.0, 1.0],
 [3.0, 1.0, 1.5],
 [3.0, 1.75, 1.0],
 [5.0, 2.0, 1.5],
 [4.0, 3.0, 2.0],
 [3.0, 2.0, 2.0],
 [4.0, 1.0, 1.5],
 [2.0, 1.0, 1.0],
 [3.0, 1.0, 1.0],
 [4.0, 1.75, 1.0],
 [3.0, 2.75, 1.0],
 [5.0, 2.5, 2.0],
 [2.0, 1.5, 1.0],
 [3.0, 2.25, 2.0],
 [3.0, 2.0, 1.5],
 [3.0, 1.75, 2.0],
 [3.0, 1.0, 1.5],
 [3.0, 1.75, 1.0],
 [4.0, 2.5, 2.0],
 [3.0, 2.5, 2.0],
 [2.0, 1.5, 3.0],
 [4.0, 1.75, 1.5],
 [3.0, 1.0, 1.5],
 [4.0, 2.75, 1.0],
 [3.0, 2.5, 1.5],
 [4.0, 1.0, 1.0],
 [4.0, 2.0, 2.0],
 [4.0, 1.0, 1.0],
 [4.0, 2.5, 2.0],
 [4.0, 2.5, 2.0],
 [4.0, 2.25, 1.0],
 [5.0, 2.75, 2.0],
 [3.0, 1.0, 2.0],
 [3.0, 1.0, 1.0],
 [3.0, 2.5, 2.0],
 [3.0, 1.0, 1.0],
 [4.0, 2.5, 2.0],
 [3.0, 1.75, 1.0],
 [3.0, 2.5, 1.0],
 [3.0, 1.0, 1.0],
 [5.0, 2.5, 1.0],
 [3.0, 1.75, 1.0],
 [2.0, 1.75, 1.0],
 [5.0, 2.25, 

In [945]:
len(x)

999

In [946]:
len(data)

999

In [947]:
y

[22.19,
 53.8,
 18.0,
 60.4,
 51.0,
 123.0,
 25.75,
 29.185,
 22.95,
 32.3,
 66.25,
 46.8,
 31.0,
 40.0,
 53.0,
 65.0,
 39.5,
 48.5,
 18.9,
 23.0,
 38.5,
 200.0,
 28.5,
 25.27,
 32.9,
 23.3,
 93.7,
 66.7,
 43.8,
 71.9,
 58.05,
 28.0,
 68.75,
 53.5,
 32.25,
 69.6,
 55.0,
 64.0,
 24.0,
 60.5,
 62.5,
 77.5,
 86.199,
 68.5,
 30.9,
 48.8,
 21.049,
 78.5,
 45.0,
 135.0,
 22.8,
 34.5,
 60.0,
 58.5,
 92.0,
 88.5,
 29.25,
 30.1,
 95.1,
 43.0,
 65.0,
 28.9,
 50.5,
 54.9,
 42.5,
 31.7625,
 97.5,
 28.7,
 20.4,
 133.0,
 104.0,
 32.5,
 57.1,
 36.0,
 34.9,
 83.25,
 38.0,
 48.0,
 41.0,
 72.0,
 39.0,
 36.0,
 35.5,
 35.6,
 31.5,
 94.0,
 30.5,
 46.1,
 21.5,
 33.5,
 24.35,
 110.0,
 15.3,
 43.0,
 70.0,
 90.5,
 24.75,
 19.9,
 31.4,
 43.75,
 85.083,
 55.5,
 69.995,
 109.0,
 29.0,
 37.5,
 46.0,
 18.85,
 68.0,
 47.0,
 59.775,
 57.0,
 27.25,
 32.995,
 48.0,
 74.05,
 51.85,
 20.5425,
 17.18,
 53.5,
 66.0,
 39.15,
 39.5,
 44.5,
 77.0,
 145.0,
 44.5,
 26.0,
 82.25,
 43.0,
 21.2,
 66.05,
 78.4,
 45.3246,
 67.5,
 19

In [948]:
x[1][2]

2.0

In [949]:
len(y)

999

In [950]:
x_max_value=0
for i in range(m):
        for j in range(3):
           x_max_value=np.max(x[i][j])
        print(x_max_value)

1.0
2.0
1.0
1.0
1.0
1.0
2.0
1.0
1.0
2.0
1.0
1.0
1.5
1.0
1.5
2.0
2.0
1.5
1.0
1.0
1.0
1.0
2.0
1.0
2.0
1.5
2.0
1.5
1.0
2.0
2.0
3.0
1.5
1.5
1.0
1.5
1.0
2.0
1.0
2.0
2.0
1.0
2.0
2.0
1.0
2.0
1.0
2.0
1.0
1.0
1.0
1.0
1.0
1.0
1.5
2.0
2.0
2.0
2.0
2.0
1.0
1.0
2.0
3.0
1.0
1.5
2.0
2.0
1.0
1.0
1.0
1.0
1.5
2.0
1.0
2.0
1.0
1.0
1.0
2.0
2.0
2.0
1.0
1.0
1.0
2.0
1.5
2.0
2.0
2.0
2.0
2.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
2.0
1.5
1.5
2.0
2.0
1.0
1.0
1.5
1.0
2.0
2.0
2.0
1.0
1.0
1.0
2.0
2.0
3.0
1.0
1.0
1.5
1.0
1.0
1.0
1.5
2.0
1.5
1.0
1.0
2.0
2.0
1.0
1.0
1.5
2.0
3.0
1.0
1.0
1.0
1.0
3.0
1.0
1.0
1.0
1.0
1.0
2.0
2.0
2.0
1.0
1.0
2.0
1.5
1.0
2.0
1.0
1.0
2.0
1.0
1.5
1.0
1.0
1.0
2.0
1.0
1.0
1.0
1.0
2.0
1.0
1.0
1.0
1.0
1.5
2.0
2.0
2.0
1.0
1.0
1.0
1.0
2.0
1.5
2.0
2.0
2.0
1.0
1.0
2.0
1.5
1.0
1.0
1.0
1.0
1.0
1.0
2.0
1.5
2.0
2.0
1.0
1.0
2.0
1.0
1.0
1.0
1.0
2.0
1.0
1.0
2.0
2.0
2.0
1.0
2.0
2.0
1.0
1.0
2.0
1.0
1.0
2.0
1.0
2.0
1.0
2.0
1.0
1.0
1.0
1.0
2.0
2.0
1.0
1.0
1.0
1.5
2.0
1.0
1.5
2.0
1.0
1.0
1.0
1.5
1.0
1.0
2.0
1.0
1.0
1.0
1.0


In [951]:
def reScale_x_y(x,y):
    m=len(data)
    x_max_value=0
    for i in range(m):
        for j in range(3):
           x_max_value=np.max(x[i][j])
    y_max_value=max(y)
    for i in range(m):
        x[i]=np.divide(x[i],x_max_value)
        y[i]=y[i]/y_max_value
    return x,y
    

In [952]:
x,y =reScale_x_y(x,y)

In [953]:
x

[array([3., 1., 1.]),
 array([3.  , 2.25, 2.  ]),
 array([2., 1., 1.]),
 array([4., 3., 1.]),
 array([3., 2., 1.]),
 array([4. , 4.5, 1. ]),
 array([3.  , 2.25, 2.  ]),
 array([3. , 1.5, 1. ]),
 array([3., 1., 1.]),
 array([3. , 2.5, 2. ]),
 array([3. , 2.5, 1. ]),
 array([2., 1., 1.]),
 array([3. , 1. , 1.5]),
 array([3.  , 1.75, 1.  ]),
 array([5. , 2. , 1.5]),
 array([4., 3., 2.]),
 array([3., 2., 2.]),
 array([4. , 1. , 1.5]),
 array([2., 1., 1.]),
 array([3., 1., 1.]),
 array([4.  , 1.75, 1.  ]),
 array([3.  , 2.75, 1.  ]),
 array([5. , 2.5, 2. ]),
 array([2. , 1.5, 1. ]),
 array([3.  , 2.25, 2.  ]),
 array([3. , 2. , 1.5]),
 array([3.  , 1.75, 2.  ]),
 array([3. , 1. , 1.5]),
 array([3.  , 1.75, 1.  ]),
 array([4. , 2.5, 2. ]),
 array([3. , 2.5, 2. ]),
 array([2. , 1.5, 3. ]),
 array([4.  , 1.75, 1.5 ]),
 array([3. , 1. , 1.5]),
 array([4.  , 2.75, 1.  ]),
 array([3. , 2.5, 1.5]),
 array([4., 1., 1.]),
 array([4., 2., 2.]),
 array([4., 1., 1.]),
 array([4. , 2.5, 2. ]),
 array([4

In [954]:
y

[0.07204545454545455,
 0.17467532467532468,
 0.05844155844155844,
 0.19610389610389609,
 0.16558441558441558,
 0.39935064935064934,
 0.0836038961038961,
 0.0947564935064935,
 0.07451298701298702,
 0.10487012987012986,
 0.2150974025974026,
 0.15194805194805194,
 0.10064935064935066,
 0.12987012987012986,
 0.17207792207792208,
 0.21103896103896103,
 0.12824675324675325,
 0.15746753246753248,
 0.061363636363636356,
 0.07467532467532467,
 0.125,
 0.6493506493506493,
 0.09253246753246754,
 0.08204545454545455,
 0.10681818181818181,
 0.07564935064935065,
 0.3042207792207792,
 0.21655844155844156,
 0.1422077922077922,
 0.23344155844155845,
 0.18847402597402596,
 0.09090909090909091,
 0.22321428571428573,
 0.1737012987012987,
 0.10470779220779221,
 0.22597402597402597,
 0.17857142857142858,
 0.2077922077922078,
 0.07792207792207792,
 0.19642857142857142,
 0.20292207792207792,
 0.25162337662337664,
 0.2798668831168831,
 0.2224025974025974,
 0.10032467532467532,
 0.15844155844155844,
 0.06834090

In [955]:
#h(x)=theta0+theta1*x1

In [956]:
y

[0.07204545454545455,
 0.17467532467532468,
 0.05844155844155844,
 0.19610389610389609,
 0.16558441558441558,
 0.39935064935064934,
 0.0836038961038961,
 0.0947564935064935,
 0.07451298701298702,
 0.10487012987012986,
 0.2150974025974026,
 0.15194805194805194,
 0.10064935064935066,
 0.12987012987012986,
 0.17207792207792208,
 0.21103896103896103,
 0.12824675324675325,
 0.15746753246753248,
 0.061363636363636356,
 0.07467532467532467,
 0.125,
 0.6493506493506493,
 0.09253246753246754,
 0.08204545454545455,
 0.10681818181818181,
 0.07564935064935065,
 0.3042207792207792,
 0.21655844155844156,
 0.1422077922077922,
 0.23344155844155845,
 0.18847402597402596,
 0.09090909090909091,
 0.22321428571428573,
 0.1737012987012987,
 0.10470779220779221,
 0.22597402597402597,
 0.17857142857142858,
 0.2077922077922078,
 0.07792207792207792,
 0.19642857142857142,
 0.20292207792207792,
 0.25162337662337664,
 0.2798668831168831,
 0.2224025974025974,
 0.10032467532467532,
 0.15844155844155844,
 0.06834090

In [957]:
theta0=1.0
theta1=2.0
theta2=1
theta3=1
alpha=0.1

In [971]:

def get_theta0_theta1(theta0,theta1,theta2,theta3):
    sumvalue=0
    m=len(data)
    for i in range(1,1000):
        for j in range(1,m+1):
            hTheta=theta0+theta1*x[j-1][0]+theta2*x[j-1][1]+theta3*x[j-1][2]
            sumvalue=sumvalue+(hTheta-y[j-1])
        theta0=theta0-alpha*(1/m)*sumvalue
        theta1=theta1-alpha*(1/m)*sumvalue
        theta2=theta2-alpha*(1/m)*sumvalue
        theta3=theta3-alpha*(1/m)*sumvalue
    return theta0,theta1,theta2,theta3
    

In [972]:
theta0,theta1,theta2,theta3=get_theta0_theta1(theta0,theta1,theta2,theta3)

In [973]:
theta0

-0.23219182208354638

In [974]:
theta1

0.7678081779164544

In [975]:
theta2

-0.23219182208354638

In [976]:
theta3

-0.23219182208354638

In [977]:
def prediction(theta0,theta1,theta2,theta3):
    y_predict=[]
    m=len(data)
    for j in range(m):
            hTheta=theta0+theta1*x[j][0]+theta2*x[j][1]+theta3*x[j][2]
            y_predict.append(hTheta)
    return y_predict

In [978]:
y_predict=prediction(theta0,theta1,theta2,theta3)

In [979]:
y_predict

[1.606849067498724,
 1.0844174678107446,
 0.8390408895822696,
 1.9102736012480857,
 1.3746572454151775,
 1.561985868122766,
 1.0844174678107446,
 1.4907531564569507,
 1.606849067498724,
 1.026369512289858,
 1.2585613343734043,
 0.8390408895822696,
 1.4907531564569507,
 1.4327052009360641,
 2.7941776902063133,
 1.6780817791645393,
 1.1424654233316311,
 2.2585613343734052,
 0.8390408895822696,
 1.606849067498724,
 2.2005133788525186,
 1.2005133788525177,
 2.561985868122767,
 0.7229449785404964,
 1.0844174678107446,
 1.2585613343734043,
 1.2005133788525177,
 1.4907531564569507,
 1.4327052009360641,
 1.7941776902063125,
 1.026369512289858,
 0.2585613343734037,
 2.0844174678107454,
 1.4907531564569507,
 1.9683215567689722,
 1.1424654233316311,
 2.3746572454151784,
 1.9102736012480857,
 2.3746572454151784,
 1.7941776902063125,
 1.7941776902063125,
 2.0844174678107454,
 2.5039379126018804,
 1.3746572454151775,
 1.606849067498724,
 1.026369512289858,
 1.606849067498724,
 1.7941776902063125,
 1

In [980]:
def calculate_cost_function():
    m=len(data)
    for i in range(m):
        sumValue=(y_predict[i]-y[i])**2
    cost_function=(1/(2*m))/sumValue
    return cost_function

In [981]:
cost_function=calculate_cost_function()

In [982]:
cost_function

0.0008282287290522553